services:
  hidden-prompt-ai:
    image: h4x3rotab/llm-sandbox:latest
    ports:
      - "8000:8000"
    environment:
      - SYSTEM_PROMPT=${SYSTEM_PROMPT:-You are a helpful assistant.}
    restart: unless-stopped
